/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnauthenticatedImport } from './routes/_unauthenticated'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as UnathenticatedSignupImport } from './routes/_unathenticated/signup'
import { Route as UnathenticatedLoginImport } from './routes/_unathenticated/login'
import { Route as AuthenticatedOinkImport } from './routes/_authenticated/oink'
import { Route as AuthenticatedAboutImport } from './routes/_authenticated/about'

// Create/Update Routes

const UnauthenticatedRoute = UnauthenticatedImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const UnathenticatedSignupRoute = UnathenticatedSignupImport.update({
  id: '/_unathenticated/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const UnathenticatedLoginRoute = UnathenticatedLoginImport.update({
  id: '/_unathenticated/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedOinkRoute = AuthenticatedOinkImport.update({
  id: '/oink',
  path: '/oink',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAboutRoute = AuthenticatedAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/oink': {
      id: '/_authenticated/oink'
      path: '/oink'
      fullPath: '/oink'
      preLoaderRoute: typeof AuthenticatedOinkImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_unathenticated/login': {
      id: '/_unathenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnathenticatedLoginImport
      parentRoute: typeof rootRoute
    }
    '/_unathenticated/signup': {
      id: '/_unathenticated/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnathenticatedSignupImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedOinkRoute: typeof AuthenticatedOinkRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedOinkRoute: AuthenticatedOinkRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof UnauthenticatedRoute
  '/about': typeof AuthenticatedAboutRoute
  '/oink': typeof AuthenticatedOinkRoute
  '/login': typeof UnathenticatedLoginRoute
  '/signup': typeof UnathenticatedSignupRoute
  '/': typeof AuthenticatedIndexRoute
}

export interface FileRoutesByTo {
  '': typeof UnauthenticatedRoute
  '/about': typeof AuthenticatedAboutRoute
  '/oink': typeof AuthenticatedOinkRoute
  '/login': typeof UnathenticatedLoginRoute
  '/signup': typeof UnathenticatedSignupRoute
  '/': typeof AuthenticatedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/oink': typeof AuthenticatedOinkRoute
  '/_unathenticated/login': typeof UnathenticatedLoginRoute
  '/_unathenticated/signup': typeof UnathenticatedSignupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/about' | '/oink' | '/login' | '/signup' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/about' | '/oink' | '/login' | '/signup' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/about'
    | '/_authenticated/oink'
    | '/_unathenticated/login'
    | '/_unathenticated/signup'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  UnathenticatedLoginRoute: typeof UnathenticatedLoginRoute
  UnathenticatedSignupRoute: typeof UnathenticatedSignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRoute,
  UnathenticatedLoginRoute: UnathenticatedLoginRoute,
  UnathenticatedSignupRoute: UnathenticatedSignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_unauthenticated",
        "/_unathenticated/login",
        "/_unathenticated/signup"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/about",
        "/_authenticated/oink",
        "/_authenticated/"
      ]
    },
    "/_unauthenticated": {
      "filePath": "_unauthenticated.tsx"
    },
    "/_authenticated/about": {
      "filePath": "_authenticated/about.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/oink": {
      "filePath": "_authenticated/oink.tsx",
      "parent": "/_authenticated"
    },
    "/_unathenticated/login": {
      "filePath": "_unathenticated/login.tsx"
    },
    "/_unathenticated/signup": {
      "filePath": "_unathenticated/signup.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
